=== Qumulo/QumuloSync/config/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "force": {
        "type": "boolean"
      },
      "log": {
        "type": "string"
      },
      "delete_non_existing": {
        "type": "boolean"
      },
      "top_dir": {
        "type": "string"
      },
      "smb": {
        "type": "object",
        "properties": {
          "shares": {
            "type": "array",
            "items": {}
          },
          "hide": {
            "type": "boolean"
          }
        },
        "required": [
          "shares",
          "hide"
        ]
      },
      "nfs": {
        "type": "object",
        "properties": {
          "exports": {
            "type": "array",
            "items": {}
          }
        },
        "required": [
          "exports"
        ]
      },
      "quota": {
        "type": "object",
        "properties": {
          "directories": {
            "type": "array",
            "items": {}
          },
          "additional_limit": {
            "type": "integer",
            "items": {}
          }
        },
        "required": [
          "directories",
          "additional_limit"
        ]
      },
      "s3": {
        "type": "object",
        "properties": {
          "buckets": {
            "type": "array",
            "items": {}
          }
        },
        "required": [
          "buckets"
        ]
      },
      "snapshot_policy": {
        "type": "object",
        "properties": {
          "policies": {
            "type": "array",
            "items": {}
          }
        },
        "required": [
          "policies"
        ]
      },
      "source": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "access_token": {
            "type": "string"
          }
        },
        "required": [
          "address",
          "username",
          "password",
          "access_token"
        ]
      },
      "destination": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "access_token": {
            "type": "string"
          }
        },
        "required": [
          "address",
          "username",
          "password",
          "access_token"
        ]
      }
    },
    "required": [
      "smb",
      "nfs",
      "quota",
      "s3",
      "snapshot_policy",
      "source",
      "destination"
    ]
  }

=== Qumulo/QumuloSync/config/config.json
{
	"force" : true,
	"log" : "DEBUG",
	"delete_non_existing": false,
	"top_dir": "",
	"smb": {
			"shares": ["all"],
			"hide": false
	},
	"nfs": {
			"exports": ["all"]
	},
	"s3": {
		"buckets": ["all"]

	},
	"snapshot_policy": {
		"policies": ["snaps", "Secondary_mins"]

	},
	"quota": {
			"directories": ["all"],
			"additional_limit":0
	},
	"source": {
		"address": "qwho.eng.qumulo.com",
	        "port": "8000",
	        "username": "admin",
	        "password": "Admin123",
	        "access_token": ""
	    },
	"destination": {
	        "address": "qwhat.eng.qumulo.com",
	        "port": "8000",
	        "username": "admin",
	        "password": "Admin123",
	        "access_token": ""
	}
}
